import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home({ ame }) {
  const d =new Date();
  let nextphase;
  let time;
  const phases=[
    "2022-01-02T00:00:00.000Z",
    "2022-01-06T00:00:00.000Z",
    "2022-01-07T12:00:00.000Z",
  ]
  for(let i=0;i<phases.length;i++){
    const c = new Date(phases[i]);
    var diff = c.getTime()-d.getTime();
    var diffdays = diff/(1000*3600*24);
    if(diffdays>0){
      nextphase=i+1 ; 
      let current_phase_ending = c.getTime()-d.getTime();
      var seconds = current_phase_ending / 1000;
      time = parseInt( seconds / 3600 );
      break;
     }

  }
  const calculate_time=(nextphase,todaydate)=>{
    let hrs;
    let current_phase_ending = nextphase-todaydate;
    var seconds = current_phase_ending / 1000;
    hrs = parseInt( seconds / 3600 );
    return hrs;
  }
  if(nextphase){
    console.log("next is phase "+nextphase)
    console.log("current phase ends in "+time+" hrs")
  }
  else{
    console.log("current phase is  "+phases.length)
    const drs= new Date(phases[phases.length-1])
    const final = calculate_time(d.getTime(),drs.getTime());
    console.log("current phase ends in "+ final +" hrs")
  }
 
  
  return (
    <div className={styles.container}>
      <Head>

        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>{ame}</h1>
        <h1 className={styles.title}>

          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >

          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
};

export const getServerSideProps = async () => {
  return {
    props: {
      ame: process.env.SRI,
    },
  }
}
